import express from "express"
import fetch from "node-fetch"
import cors from "cors"
import { nanoid } from "nanoid"


const app = express()

app.use(express.json())
app.use(cors())

const port = 5000

app.get("/api/swiggy", async (req, res) => {
  try {
    const apiUrl = "https://www.swiggy.com/dapi/restaurants/list/v5?lat=17.4478225&lng=78.44648579999999&is-seo-homepage-enabled=true&page_type=DESKTOP_WEB_LISTING";

    const response = await fetch(apiUrl, {
      headers: {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
        "Accept": "application/json",
        "Accept-Language": "en-IN,en;q=0.9",
        "Referer": "https://www.swiggy.com/",
        "Origin": "https://www.swiggy.com",
      },
    });

    console.log("Swiggy response status:", response.status);

    if (!response.ok) {
      return res.status(response.status).json({ error: "Swiggy API failed" });
    }

    const data = await response.json();
    res.json(data);
  } catch (error) {
    console.error("Fetch error:", error.message);
    res.status(500).json({ error: "Server error", message: error.message });
  }
});

// function getCurrentDateKey() {
//   const now = new Date();
//   const year = now.getFullYear();
//   const month = String(now.getMonth() + 1).padStart(2, '0');
//   const day = String(now.getDate()).padStart(2, '0');
//   return `${year}${month}${day}`; // e.g., "20250725"
// }

// function generateHybridLeadId() {
//   const date = getCurrentDateKey();
//   const shortId = nanoid(8).toUpperCase(); // 8-character unique string
//   return `H-LEAD-${date}-${shortId}`;
// }

// // Example:
// const leadId = generateHybridLeadId();
// console.log(leadId); // H-LEAD-20250725-X7K9L2FQ

// const allLeads =  [
//         {
//             "_id": "681cf440adb9d7c64aabf873",
//             "salutation": "",
//             "name": "United launch alliance Elizabeth",
//             "phone": "IT Vendor Manager",
//             "email": "elizabeth.hanley@ulalaunch.com",
//             "company": "Hanley",
//             "website": "",
//             "title": "",
//             "leadSource": "",
//             "industry": "",
//             "leadStatus": "",
//             "requirement": "",
//             "currentLandscape": "",
//             "followUp": "No longer working with ULA",
//             "type": "",
//             "cem": "",
//             "region": "",
//             "houseNumber": "",
//             "street": "",
//             "pincodeOrZipcode": "",
//             "city": "",
//             "__v": 0,
//             "createdAt": "2025-05-08T18:13:21.167Z",
//             "updatedAt": "2025-05-08T18:13:21.167Z"
//         },
//         {
//             "_id": "681cf440adb9d7c64aabf854",
//             "salutation": "",
//             "name": "Cinthia  De Vries",
//             "phone": "(920) 319-9148",
//             "email": "devriescinthia@johndeere.com",
//             "company": "John Deere",
//             "website": "",
//             "title": "",
//             "leadSource": "",
//             "industry": "",
//             "leadStatus": "",
//             "requirement": "S/4 HANA implementation",
//             "currentLandscape": "",
//             "followUp": " Shared the DMAG materials and sent up meeting for next Friday",
//             "type": "",
//             "cem": "Anirudh",
//             "region": "Midwest",
//             "houseNumber": "",
//             "street": "",
//             "pincodeOrZipcode": "",
//             "city": "",
//             "__v": 0,
//             "createdAt": "2025-05-08T18:13:21.165Z",
//             "updatedAt": "2025-06-18T13:04:24.484Z"
//         },
//         {
//             "_id": "681cf440adb9d7c64aabf858",
//             "salutation": "",
//             "name": "Leann  Bolte",
//             "phone": "",
//             "email": "bolteleannR@johndeere.com",
//             "company": "John Deere",
//             "website": "",
//             "title": "Finance Product",
//             "leadSource": "",
//             "industry": "",
//             "leadStatus": "",
//             "requirement": "S/4 HANA support ",
//             "currentLandscape": "ECC ",
//             "followUp": "Shared resources list",
//             "type": "",
//             "cem": "Anirudh",
//             "region": "Midwest",
//             "houseNumber": "",
//             "street": "",
//             "pincodeOrZipcode": "",
//             "city": "",
//             "__v": 0,
//             "createdAt": "2025-05-08T18:13:21.165Z",
//             "updatedAt": "2025-06-18T13:04:34.082Z"
//         },
//         {
//             "_id": "681cf440adb9d7c64aabf85f",
//             "salutation": "",
//             "name": "Jeanne Brook",
//             "phone": "7154439471",
//             "email": "jbrook@mcheese.com",
//             "company": "Marathon cheese corp ",
//             "website": "",
//             "title": "",
//             "leadSource": "",
//             "industry": "",
//             "leadStatus": "",
//             "requirement": "S/4 HANA assessment ",
//             "currentLandscape": "ECC6",
//             "followUp": "Shared materials / Conduct Free assesment on her ECC system/ Set up a meeting next week. ",
//             "type": "",
//             "cem": "Anirudh",
//             "region": "Midwest",
//             "houseNumber": "",
//             "street": "",
//             "pincodeOrZipcode": "",
//             "city": "",
//             "__v": 0,
//             "createdAt": "2025-05-08T18:13:21.166Z",
//             "updatedAt": "2025-06-18T13:04:21.481Z"
//         },
//         {
//             "_id": "681cf440adb9d7c64aabf850",
//             "salutation": "",
//             "name": "Sheila Cisneros",
//             "phone": "2628932784",
//             "email": "S.cisneros@owi.com",
//             "company": "Old World Indurstries",
//             "website": "",
//             "title": "",
//             "leadSource": "",
//             "industry": "",
//             "leadStatus": "",
//             "requirement": "Cleansing and governanace for DMAG",
//             "currentLandscape": "",
//             "followUp": " Sent materials and set up demo meeting for cleansing and governance",
//             "type": "",
//             "cem": "Anirudh",
//             "region": "Midwest",
//             "houseNumber": "",
//             "street": "",
//             "pincodeOrZipcode": "",
//             "city": "",
//             "__v": 0,
//             "createdAt": "2025-05-08T18:13:21.165Z",
//             "updatedAt": "2025-06-18T13:04:12.756Z"
//         },
//         {
//             "_id": "681cf440adb9d7c64aabf84c",
//             "salutation": "",
//             "name": "Tami Walstrom",
//             "phone": "248-781-3086, 3135698900",
//             "email": "tamiw@dhcdg.net",
//             "company": "Dearborn",
//             "website": "",
//             "title": "SAP Manager",
//             "leadSource": "",
//             "industry": "",
//             "leadStatus": "",
//             "requirement": "Send the Dmag Materials (Data Mapping)",
//             "currentLandscape": "Implementing S4 HANA 1909 Private cloud Addition (greenfield",
//             "followUp": " meeting on 14th / didn't respond",
//             "type": "",
//             "cem": "Hima",
//             "region": "Midwest",
//             "houseNumber": "",
//             "street": "",
//             "pincodeOrZipcode": "",
//             "city": "",
//             "__v": 0,
//             "createdAt": "2025-05-08T18:13:21.165Z",
//             "updatedAt": "2025-06-18T11:47:22.548Z"
//         },
//         {
//             "_id": "681cf440adb9d7c64aabf85c",
//             "salutation": "",
//             "name": "Brad Good ",
//             "phone": "502-540-6131",
//             "email": "brad.good@louisvillemsd.org",
//             "company": "Metro emergency service",
//             "website": "",
//             "title": "",
//             "leadSource": "",
//             "industry": "",
//             "leadStatus": "",
//             "requirement": "S/4 HANA migration assesment",
//             "currentLandscape": "ECC ",
//             "followUp": "follow up meeting on assessment ",
//             "type": "",
//             "cem": "Hima",
//             "region": "Midwest",
//             "houseNumber": "",
//             "street": "",
//             "pincodeOrZipcode": "",
//             "city": "",
//             "__v": 0,
//             "createdAt": "2025-05-08T18:13:21.166Z",
//             "updatedAt": "2025-06-18T11:47:32.232Z"
//         },
//         {
//             "_id": "681cf440adb9d7c64aabf86d",
//             "salutation": "",
//             "name": "David  Levy",
//             "phone": "7737964954",
//             "email": "dlevy@objectiveERP.com",
//             "company": "Objective ERP",
//             "website": "",
//             "title": "Practice Director",
//             "leadSource": "",
//             "industry": "",
//             "leadStatus": "",
//             "requirement": "Salesforce commerce cloud 4 positions open ",
//             "currentLandscape": "Recruiter",
//             "followUp": "Shares sales force commerce cloud resources",
//             "type": "",
//             "cem": "Hima",
//             "region": "Midwest",
//             "houseNumber": "",
//             "street": "",
//             "pincodeOrZipcode": "",
//             "city": "",
//             "__v": 0,
//             "createdAt": "2025-05-08T18:13:21.167Z",
//             "updatedAt": "2025-06-18T11:47:40.881Z"
//         },
//         {
//             "_id": "681cf440adb9d7c64aabf885",
//             "salutation": "",
//             "name": "Fallon Chattaway",
//             "phone": "1 713-483-9090",
//             "email": "fallon.chattaway@accenture.com",
//             "company": "Accenture",
//             "website": "",
//             "title": "Marketing Lead",
//             "leadSource": "",
//             "industry": "",
//             "requirement": "",
//             "currentLandscape": "",
//             "followUp": "",
//             "type": "",
//             "cem": "Karen",
//             "region": "Midwest & TX",
//             "houseNumber": "",
//             "street": "",
//             "pincodeOrZipcode": "",
//             "city": "",
//             "country": "",
//             "__v": 0,
//             "createdAt": "2025-05-08T18:13:21.168Z",
//             "updatedAt": "2025-06-18T13:18:26.904Z"
//         },
//         {
//             "_id": "681cf440adb9d7c64aabf8b4",
//             "salutation": "",
//             "name": "Justin Lester",
//             "phone": "972-673-2000",
//             "email": "justin.lester@denbury.com",
//             "company": "DENBURY INC",
//             "website": "",
//             "title": "DIRECTOR SCM / EAM",
//             "leadSource": "",
//             "industry": "",
//             "requirement": "",
//             "currentLandscape": "",
//             "followUp": "",
//             "type": "",
//             "cem": "Karen",
//             "region": "Midwest & TX",
//             "houseNumber": "",
//             "street": "",
//             "pincodeOrZipcode": "",
//             "city": "",
//             "country": "",
//             "__v": 0,
//             "createdAt": "2025-05-08T18:13:21.173Z",
//             "updatedAt": "2025-06-18T13:15:01.575Z"
//         },
//         {
//             "_id": "681cf440adb9d7c64aabf8b5",
//             "salutation": "",
//             "name": "Nathan Midcap",
//             "phone": "9726732305",
//             "email": "nathan.midcap@denbury.com",
//             "company": "Denbury Inc.",
//             "website": "",
//             "title": "Sr IT Compliance / Business Analyst",
//             "leadSource": "",
//             "industry": "",
//             "requirement": "",
//             "currentLandscape": "",
//             "followUp": "",
//             "type": "",
//             "cem": "Karen",
//             "region": "Midwest & TX",
//             "houseNumber": "",
//             "street": "",
//             "pincodeOrZipcode": "",
//             "city": "",
//             "country": "",
//             "__v": 0,
//             "createdAt": "2025-05-08T18:13:21.173Z",
//             "updatedAt": "2025-06-18T13:18:39.340Z"
//         },
//         {
//             "_id": "681cf440adb9d7c64aabf8b7",
//             "salutation": "",
//             "name": "Heath Satterfield",
//             "phone": "",
//             "email": "heath.satterfield@dvn.com",
//             "company": "Devon",
//             "website": "",
//             "title": "",
//             "leadSource": "",
//             "industry": "",
//             "requirement": "",
//             "currentLandscape": "",
//             "followUp": "",
//             "type": "",
//             "cem": "Karen",
//             "region": "Midwest & TX",
//             "houseNumber": "",
//             "street": "",
//             "pincodeOrZipcode": "",
//             "city": "",
//             "country": "",
//             "__v": 0,
//             "createdAt": "2025-05-08T18:13:21.173Z",
//             "updatedAt": "2025-06-18T13:18:48.159Z"
//         },
//         {
//             "_id": "681cf440adb9d7c64aabf8be",
//             "salutation": "",
//             "name": "Sarika Gattawar",
//             "phone": "8328789103",
//             "email": "sgatt@equinor.com",
//             "company": "Equinor",
//             "website": "",
//             "title": "Lead IT Analyst",
//             "leadSource": "",
//             "industry": "",
//             "requirement": "",
//             "currentLandscape": "",
//             "followUp": "",
//             "type": "",
//             "cem": "Karen",
//             "region": "Midwest & TX",
//             "houseNumber": "",
//             "street": "",
//             "pincodeOrZipcode": "",
//             "city": "",
//             "country": "",
//             "__v": 0,
//             "createdAt": "2025-05-08T18:13:21.174Z",
//             "updatedAt": "2025-06-18T13:14:53.599Z"
//         },
//         {
//             "_id": "681cf440adb9d7c64aabf8c0",
//             "salutation": "",
//             "name": "Kris Knobles",
//             "phone": "9368004024",
//             "email": "kkno@equinor.com",
//             "company": "Equinor",
//             "website": "",
//             "title": "Accounting Leader",
//             "leadSource": "",
//             "industry": "",
//             "requirement": "",
//             "currentLandscape": "",
//             "followUp": "",
//             "type": "",
//             "cem": "Karen",
//             "region": "Midwest & TX",
//             "houseNumber": "",
//             "street": "",
//             "pincodeOrZipcode": "",
//             "city": "",
//             "country": "",
//             "__v": 0,
//             "createdAt": "2025-05-08T18:13:21.174Z",
//             "updatedAt": "2025-06-18T13:15:25.488Z"
//         },
//         {
//             "_id": "681cf440adb9d7c64aabf8c1",
//             "salutation": "",
//             "name": "Todd Sandig",
//             "phone": "18326686748",
//             "email": "ricsa@equinor.com",
//             "company": "Equinor",
//             "website": "",
//             "title": "Leader Finance",
//             "leadSource": "",
//             "industry": "",
//             "requirement": "",
//             "currentLandscape": "",
//             "followUp": "",
//             "type": "",
//             "cem": "Karen",
//             "region": "Midwest & TX",
//             "houseNumber": "",
//             "street": "",
//             "pincodeOrZipcode": "",
//             "city": "",
//             "country": "",
//             "__v": 0,
//             "createdAt": "2025-05-08T18:13:21.174Z",
//             "updatedAt": "2025-06-18T13:18:57.640Z"
//         },
//         {
//             "_id": "681cf440adb9d7c64aabf8c3",
//             "salutation": "",
//             "name": "Augusto Castro",
//             "phone": "18326596145",
//             "email": "acast@equinor.com",
//             "company": "Equinor previously known as Statoil",
//             "website": "",
//             "title": "IT Leader",
//             "leadSource": "",
//             "industry": "",
//             "requirement": "",
//             "currentLandscape": "",
//             "followUp": "",
//             "type": "",
//             "cem": "Karen",
//             "region": "Midwest & TX",
//             "houseNumber": "",
//             "street": "",
//             "pincodeOrZipcode": "",
//             "city": "",
//             "country": "",
//             "__v": 0,
//             "createdAt": "2025-05-08T18:13:21.174Z",
//             "updatedAt": "2025-06-18T13:15:09.781Z"
//         },
//         {
//             "_id": "681cf440adb9d7c64aabf8d0",
//             "salutation": "",
//             "name": "Purushotham Ineni",
//             "phone": "2813866781",
//             "email": "pineni@goldenpasslng.com",
//             "company": "Golden Pass LNG ",
//             "website": "",
//             "title": "SAP Delivery Manager",
//             "leadSource": "",
//             "industry": "",
//             "requirement": "",
//             "currentLandscape": "",
//             "followUp": "",
//             "type": "",
//             "cem": "Karen",
//             "region": "Midwest & TX",
//             "houseNumber": "",
//             "street": "",
//             "pincodeOrZipcode": "",
//             "city": "",
//             "country": "",
//             "__v": 0,
//             "createdAt": "2025-05-08T18:13:21.175Z",
//             "updatedAt": "2025-06-18T13:16:28.977Z"
//         },
//         {
//             "_id": "681cf440adb9d7c64aabf8d4",
//             "salutation": "",
//             "name": "Robert Serrata",
//             "phone": "3616523742",
//             "email": "reserrata@google.com",
//             "company": "Google",
//             "website": "",
//             "title": "Customer Engineer Manager",
//             "leadSource": "",
//             "industry": "",
//             "requirement": "",
//             "currentLandscape": "",
//             "followUp": "",
//             "type": "",
//             "cem": "Karen",
//             "region": "Midwest & TX",
//             "houseNumber": "",
//             "street": "",
//             "pincodeOrZipcode": "",
//             "city": "",
//             "country": "",
//             "__v": 0,
//             "createdAt": "2025-05-08T18:13:21.175Z",
//             "updatedAt": "2025-06-18T13:19:06.797Z"
//         },
//         {
//             "_id": "681cf440adb9d7c64aabf8db",
//             "salutation": "",
//             "name": "Veronica Calvillo",
//             "phone": "7132892913",
//             "email": "vcalvillo@hilcorp.com",
//             "company": "HILCORP ENERGY COMPANY",
//             "website": "",
//             "title": "IT System Analyst - SAP FICO",
//             "leadSource": "",
//             "industry": "",
//             "requirement": "",
//             "currentLandscape": "",
//             "followUp": "",
//             "type": "",
//             "cem": "Karen",
//             "region": "Midwest & TX",
//             "houseNumber": "",
//             "street": "",
//             "pincodeOrZipcode": "",
//             "city": "",
//             "country": "",
//             "__v": 0,
//             "createdAt": "2025-05-08T18:13:21.175Z",
//             "updatedAt": "2025-06-18T13:17:57.954Z"
//         },
//         {
//             "_id": "681cf440adb9d7c64aabf8e6",
//             "salutation": "",
//             "name": "Sri Karthik",
//             "phone": "7132751804",
//             "email": "sri@innovapptive.com",
//             "company": "Innovapptive Inc.",
//             "website": "",
//             "title": "EVP - Solutions",
//             "leadSource": "",
//             "industry": "",
//             "requirement": "",
//             "currentLandscape": "",
//             "followUp": "",
//             "type": "",
//             "cem": "Karen",
//             "region": "Midwest & TX",
//             "houseNumber": "",
//             "street": "",
//             "pincodeOrZipcode": "",
//             "city": "",
//             "country": "",
//             "__v": 0,
//             "createdAt": "2025-05-08T18:13:21.176Z",
//             "updatedAt": "2025-06-18T13:16:36.539Z"
//         },
//         {
//             "_id": "681cf440adb9d7c64aabf8ea",
//             "salutation": "",
//             "name": "Vinod ",
//             "phone": "651-242-0744",
//             "email": "Devulapallyvinod@johndeer.com",
//             "company": "John Deer",
//             "website": "",
//             "title": "",
//             "leadSource": "",
//             "industry": "",
//             "requirement": "",
//             "currentLandscape": "",
//             "followUp": "",
//             "type": "",
//             "cem": "Karen",
//             "region": "Midwest & TX",
//             "houseNumber": "",
//             "street": "",
//             "pincodeOrZipcode": "",
//             "city": "",
//             "country": "",
//             "__v": 0,
//             "createdAt": "2025-05-08T18:13:21.176Z",
//             "updatedAt": "2025-06-18T13:18:07.487Z"
//         },
//         {
//             "_id": "681cf440adb9d7c64aabf8eb",
//             "salutation": "",
//             "name": "Cinthia  De Vries",
//             "phone": "(920) 319-9148",
//             "email": "devriescinthia@johndeere.com",
//             "company": "John Deere",
//             "website": "",
//             "title": "",
//             "leadSource": "",
//             "industry": "",
//             "requirement": "",
//             "currentLandscape": "",
//             "followUp": "",
//             "type": "",
//             "cem": "Karen",
//             "region": "Midwest & TX",
//             "houseNumber": "",
//             "street": "",
//             "pincodeOrZipcode": "",
//             "city": "",
//             "country": "",
//             "__v": 0,
//             "createdAt": "2025-05-08T18:13:21.176Z",
//             "updatedAt": "2025-06-18T13:15:40.732Z"
//         },
//         {
//             "_id": "681cf440adb9d7c64aabf8ec",
//             "salutation": "",
//             "name": "Syam Mukiri",
//             "phone": "5637420686",
//             "email": "gurramkrishna@johndeere.com",
//             "company": "John Deere",
//             "website": "",
//             "title": "Software Analyst",
//             "leadSource": "",
//             "industry": "",
//             "requirement": "",
//             "currentLandscape": "",
//             "followUp": "",
//             "type": "",
//             "cem": "Karen",
//             "region": "Midwest & TX",
//             "houseNumber": "",
//             "street": "",
//             "pincodeOrZipcode": "",
//             "city": "",
//             "country": "",
//             "__v": 0,
//             "createdAt": "2025-05-08T18:13:21.176Z",
//             "updatedAt": "2025-06-18T13:15:50.464Z"
//         },
//         {
//             "_id": "681cf440adb9d7c64aabf8ed",
//             "salutation": "",
//             "name": "Satya Narayana ",
//             "phone": "2488080828",
//             "email": "",
//             "company": "John Deere",
//             "website": "",
//             "title": "",
//             "leadSource": "",
//             "industry": "",
//             "requirement": "",
//             "currentLandscape": "",
//             "followUp": "",
//             "type": "",
//             "cem": "Karen",
//             "region": "Midwest & TX",
//             "houseNumber": "",
//             "street": "",
//             "pincodeOrZipcode": "",
//             "city": "",
//             "country": "",
//             "__v": 0,
//             "createdAt": "2025-05-08T18:13:21.176Z",
//             "updatedAt": "2025-06-18T13:16:51.231Z"
//         },
//         {
//             "_id": "681cf440adb9d7c64aabf900",
//             "salutation": "",
//             "name": "Tammie King",
//             "phone": "7154439342",
//             "email": "tammie.king@marathoncheese.com",
//             "company": "Marathon cheese corp ",
//             "website": "",
//             "title": "",
//             "leadSource": "",
//             "industry": "",
//             "requirement": "",
//             "currentLandscape": "",
//             "followUp": "",
//             "type": "",
//             "cem": "Karen",
//             "region": "Midwest & TX",
//             "houseNumber": "",
//             "street": "",
//             "pincodeOrZipcode": "",
//             "city": "",
//             "country": "",
//             "__v": 0,
//             "createdAt": "2025-05-08T18:13:21.177Z",
//             "updatedAt": "2025-06-18T13:27:03.533Z"
//         },
//         {
//             "_id": "681cf440adb9d7c64aabf909",
//             "salutation": "",
//             "name": "David  Levy",
//             "phone": "7737964954",
//             "email": "dlevy@objectiveERP.com",
//             "company": "Objective ERP",
//             "website": "",
//             "title": "Practice Director",
//             "leadSource": "",
//             "industry": "",
//             "requirement": "",
//             "currentLandscape": "",
//             "followUp": "",
//             "type": "",
//             "cem": "Karen",
//             "region": "Midwest & TX",
//             "houseNumber": "",
//             "street": "",
//             "pincodeOrZipcode": "",
//             "city": "",
//             "country": "",
//             "__v": 0,
//             "createdAt": "2025-05-08T18:13:21.177Z",
//             "updatedAt": "2025-06-18T13:19:17.319Z"
//         },
//         {
//             "_id": "681cf440adb9d7c64aabf90f",
//             "salutation": "",
//             "name": "Bill Grow",
//             "phone": "4054344989",
//             "email": "bgrow@obe.com",
//             "company": "OldCastle building",
//             "website": "",
//             "title": "",
//             "leadSource": "",
//             "industry": "",
//             "requirement": "",
//             "currentLandscape": "",
//             "followUp": "",
//             "type": "",
//             "cem": "Karen",
//             "region": "Midwest & TX",
//             "houseNumber": "",
//             "street": "",
//             "pincodeOrZipcode": "",
//             "city": "",
//             "country": "",
//             "__v": 0,
//             "createdAt": "2025-05-08T18:13:21.177Z",
//             "updatedAt": "2025-06-18T13:18:17.374Z"
//         },
//         {
//             "_id": "681cf440adb9d7c64aabf918",
//             "salutation": "",
//             "name": "pam rogers",
//             "phone": "",
//             "email": "progers@parpacific.com",
//             "company": "par pacific holdings ",
//             "website": "",
//             "title": "",
//             "leadSource": "",
//             "industry": "",
//             "requirement": "",
//             "currentLandscape": "",
//             "followUp": "",
//             "type": "",
//             "cem": "Karen",
//             "region": "Midwest & TX",
//             "houseNumber": "",
//             "street": "",
//             "pincodeOrZipcode": "",
//             "city": "",
//             "country": "",
//             "__v": 0,
//             "createdAt": "2025-05-08T18:13:21.178Z",
//             "updatedAt": "2025-06-18T13:17:00.677Z"
//         },
//         {
//             "_id": "681cf440adb9d7c64aabf91c",
//             "salutation": "",
//             "name": "Ryan Quinonez",
//             "phone": "469-835-5559",
//             "email": "Ryan.Quinonez@pathlock.com",
//             "company": "Pathlock",
//             "website": "",
//             "title": "Senior Product Marketing Manager",
//             "leadSource": "",
//             "industry": "",
//             "requirement": "",
//             "currentLandscape": "",
//             "followUp": "",
//             "type": "",
//             "cem": "Karen",
//             "region": "Midwest & TX",
//             "houseNumber": "",
//             "street": "",
//             "pincodeOrZipcode": "",
//             "city": "",
//             "country": "",
//             "__v": 0,
//             "createdAt": "2025-05-08T18:13:21.178Z",
//             "updatedAt": "2025-06-18T13:16:21.399Z"
//         },
//         {
//             "_id": "681cf440adb9d7c64aabf921",
//             "salutation": "",
//             "name": "Naveen Pandrangi",
//             "phone": "832-765-5880",
//             "email": "naveen.pandrangi@p66.com",
//             "company": "Phillips 66",
//             "website": "",
//             "title": "GM, Digital IT, Business Solutions Refining & Midstream",
//             "leadSource": "",
//             "industry": "",
//             "requirement": "",
//             "currentLandscape": "",
//             "followUp": "",
//             "type": "",
//             "cem": "Karen",
//             "region": "Midwest & TX",
//             "houseNumber": "",
//             "street": "",
//             "pincodeOrZipcode": "",
//             "city": "",
//             "country": "",
//             "__v": 0,
//             "createdAt": "2025-05-08T18:13:21.178Z",
//             "updatedAt": "2025-06-18T13:15:58.174Z"
//         },
//         {
//             "_id": "681cf440adb9d7c64aabf92d",
//             "salutation": "",
//             "name": "Jason Whitfield",
//             "phone": "5122287711",
//             "email": "jawhitfi@redhat.com",
//             "company": "Red Hat",
//             "website": "",
//             "title": "Sales",
//             "leadSource": "",
//             "industry": "",
//             "requirement": "",
//             "currentLandscape": "",
//             "followUp": "",
//             "type": "",
//             "cem": "Karen",
//             "region": "Midwest & TX",
//             "houseNumber": "",
//             "street": "",
//             "pincodeOrZipcode": "",
//             "city": "",
//             "__v": 0,
//             "createdAt": "2025-05-08T18:13:21.178Z",
//             "updatedAt": "2025-06-18T13:25:26.318Z"
//         },
//         {
//             "_id": "681cf440adb9d7c64aabf92f",
//             "salutation": "",
//             "name": "Steve Ostrom",
//             "phone": "972-533-8845",
//             "email": "Steve.Ostrom@redwood.com",
//             "company": "Redwood",
//             "website": "",
//             "title": "Solutions Engineer",
//             "leadSource": "",
//             "industry": "",
//             "requirement": "",
//             "currentLandscape": "",
//             "followUp": "",
//             "type": "",
//             "cem": "Karen",
//             "region": "Midwest & TX",
//             "houseNumber": "",
//             "street": "",
//             "pincodeOrZipcode": "",
//             "city": "",
//             "__v": 0,
//             "createdAt": "2025-05-08T18:13:21.178Z",
//             "updatedAt": "2025-06-18T13:25:13.941Z"
//         },
//         {
//             "_id": "681cf440adb9d7c64aabf948",
//             "salutation": "",
//             "name": "Etchane Towers",
//             "phone": "7135421322",
//             "email": "etchane.towers@sap.com",
//             "company": "SAP",
//             "website": "",
//             "title": "Director ",
//             "leadSource": "",
//             "industry": "",
//             "requirement": "",
//             "currentLandscape": "",
//             "followUp": "",
//             "type": "",
//             "cem": "Karen",
//             "region": "Midwest & TX",
//             "houseNumber": "",
//             "street": "",
//             "pincodeOrZipcode": "",
//             "city": "",
//             "__v": 0,
//             "createdAt": "2025-05-08T18:13:21.180Z",
//             "updatedAt": "2025-06-18T13:27:21.503Z"
//         },
//         {
//             "_id": "681cf440adb9d7c64aabf949",
//             "salutation": "",
//             "name": "Grant Vittitow",
//             "phone": "945-300-9413",
//             "email": "grant.vittitow@sap.com",
//             "company": "SAP",
//             "website": "",
//             "title": "Industry Account Executive",
//             "leadSource": "",
//             "industry": "",
//             "requirement": "",
//             "currentLandscape": "",
//             "followUp": "",
//             "type": "",
//             "cem": "Karen",
//             "region": "Midwest & TX",
//             "houseNumber": "",
//             "street": "",
//             "pincodeOrZipcode": "",
//             "city": "",
//             "__v": 0,
//             "createdAt": "2025-05-08T18:13:21.180Z",
//             "updatedAt": "2025-06-18T13:25:20.404Z"
//         },
//         {
//             "_id": "681cf440adb9d7c64aabf938",
//             "salutation": "",
//             "name": "Chris Zerlaut",
//             "phone": "6502670123`",
//             "email": "chris.zerlaut@sap.com",
//             "company": "SAP",
//             "website": "",
//             "title": "Senior Director",
//             "leadSource": "",
//             "industry": "",
//             "requirement": "",
//             "currentLandscape": "",
//             "followUp": "",
//             "type": "",
//             "cem": "Karen",
//             "region": "Midwest & TX",
//             "houseNumber": "",
//             "street": "",
//             "pincodeOrZipcode": "",
//             "city": "",
//             "__v": 0,
//             "createdAt": "2025-05-08T18:13:21.179Z",
//             "updatedAt": "2025-06-18T13:27:33.742Z"
//         },
//         {
//             "_id": "681cf440adb9d7c64aabf941",
//             "salutation": "",
//             "name": "Chelsea Hall",
//             "phone": "9722094881",
//             "email": "chelsea.hall@sap.com",
//             "company": "SAP",
//             "website": "",
//             "title": "Field Marketing",
//             "leadSource": "",
//             "industry": "",
//             "requirement": "",
//             "currentLandscape": "",
//             "followUp": "",
//             "type": "",
//             "cem": "Karen",
//             "region": "Midwest & TX",
//             "houseNumber": "",
//             "street": "",
//             "pincodeOrZipcode": "",
//             "city": "",
//             "__v": 0,
//             "createdAt": "2025-05-08T18:13:21.179Z",
//             "updatedAt": "2025-06-18T13:27:46.960Z"
//         },
//         {
//             "_id": "681cf440adb9d7c64aabf7f6",
//             "salutation": "",
//             "name": "Mular  Karanth",
//             "phone": "770-403-6453",
//             "email": "mkaranth@bbandt.com",
//             "company": "BB&T",
//             "website": "",
//             "title": "Senior VP",
//             "leadSource": "",
//             "industry": "",
//             "leadStatus": "",
//             "requirement": "",
//             "followUp": "",
//             "type": "",
//             "cem": "Priya",
//             "region": "West Coast",
//             "houseNumber": "",
//             "street": "",
//             "pincodeOrZipcode": "",
//             "city": "",
//             "country": "",
//             "__v": 0,
//             "createdAt": "2025-05-08T18:13:21.159Z",
//             "updatedAt": "2025-05-08T18:13:21.159Z"
//         },
//         {
//             "_id": "681cf440adb9d7c64aabf76f",
//             "salutation": "",
//             "name": "Darren Keenan ",
//             "phone": "9168744596",
//             "email": "darren.keenan@countyofsacramento.com",
//             "company": "County of Sacramento",
//             "website": "",
//             "title": "IT Director",
//             "leadSource": "",
//             "industry": "",
//             "leadStatus": "",
//             "requirement": "",
//             "followUp": "",
//             "type": "",
//             "cem": "Priya",
//             "region": "West Coast",
//             "houseNumber": "",
//             "street": "",
//             "pincodeOrZipcode": "",
//             "city": "",
//             "country": "",
//             "__v": 0,
//             "createdAt": "2025-05-08T18:13:21.152Z",
//             "updatedAt": "2025-05-08T18:13:21.152Z"
//         },
//         {
//             "_id": "681cf440adb9d7c64aabf848",
//             "salutation": "",
//             "name": "Surender Kandakatla",
//             "phone": "4082059975",
//             "email": "surender.kandakatla@ejgallo.com",
//             "company": "E & J Gallo",
//             "website": "",
//             "title": "SAP Security Sr.Manager",
//             "leadSource": "",
//             "industry": "",
//             "leadStatus": "",
//             "requirement": "",
//             "followUp": "",
//             "type": "",
//             "cem": "Priya",
//             "region": "West Coast",
//             "houseNumber": "",
//             "street": "",
//             "pincodeOrZipcode": "",
//             "city": "",
//             "country": "",
//             "__v": 0,
//             "createdAt": "2025-05-08T18:13:21.165Z",
//             "updatedAt": "2025-05-08T18:13:21.165Z"
//         },
//         {
//             "_id": "681cf440adb9d7c64aabf762",
//             "salutation": "",
//             "name": "TJ Baafi",
//             "phone": "6123885802",
//             "email": "thomas.baafi.iii@ibm.com",
//             "company": "IBM",
//             "website": "",
//             "title": "Global Product Leader, IBM Cloud for SAP, GTM",
//             "leadSource": "",
//             "industry": "",
//             "leadStatus": "",
//             "requirement": "",
//             "followUp": "",
//             "type": "",
//             "cem": "Priya",
//             "region": "West Coast",
//             "houseNumber": "",
//             "street": "",
//             "pincodeOrZipcode": "",
//             "city": "",
//             "country": "",
//             "__v": 0,
//             "createdAt": "2025-05-08T18:13:21.152Z",
//             "updatedAt": "2025-05-08T18:13:21.152Z"
//         },
//         {
//             "_id": "681cf440adb9d7c64aabf797",
//             "salutation": "",
//             "name": "Hong Kwok",
//             "phone": "8886708889",
//             "email": "hkwok@infotech.com",
//             "company": "Infotech",
//             "website": "",
//             "title": "Practice Lead",
//             "leadSource": "",
//             "industry": "",
//             "leadStatus": "",
//             "requirement": "",
//             "followUp": "",
//             "type": "",
//             "cem": "Priya",
//             "region": "West Coast",
//             "houseNumber": "",
//             "street": "",
//             "pincodeOrZipcode": "",
//             "city": "",
//             "country": "",
//             "__v": 0,
//             "createdAt": "2025-05-08T18:13:21.154Z",
//             "updatedAt": "2025-05-08T18:13:21.154Z"
//         },
//         {
//             "_id": "681cf440adb9d7c64aabf782",
//             "salutation": "",
//             "name": "praveen moturu",
//             "phone": "3123440159",
//             "email": "PRAVEEN.MOTURU@EFFEM.COM",
//             "company": "Mars, Inc.",
//             "website": "",
//             "title": "VP, Chief Enterprise Architect",
//             "leadSource": "",
//             "industry": "",
//             "leadStatus": "",
//             "requirement": "",
//             "followUp": "",
//             "type": "",
//             "cem": "Priya",
//             "region": "West Coast",
//             "houseNumber": "",
//             "street": "",
//             "pincodeOrZipcode": "",
//             "city": "",
//             "country": "",
//             "__v": 0,
//             "createdAt": "2025-05-08T18:13:21.153Z",
//             "updatedAt": "2025-05-08T18:13:21.153Z"
//         },
//         {
//             "_id": "681cf440adb9d7c64aabf783",
//             "salutation": "",
//             "name": "Kamala Tummala",
//             "phone": "9497276900",
//             "email": "ktummala@mazdausa.com",
//             "company": "Mazda",
//             "website": "",
//             "title": "Business System Analyst / Developer",
//             "leadSource": "",
//             "industry": "",
//             "leadStatus": "",
//             "requirement": "",
//             "followUp": "",
//             "type": "",
//             "cem": "Priya",
//             "region": "West Coast",
//             "houseNumber": "",
//             "street": "",
//             "pincodeOrZipcode": "",
//             "city": "",
//             "country": "USA",
//             "__v": 0,
//             "createdAt": "2025-05-08T18:13:21.153Z",
//             "updatedAt": "2025-05-08T18:13:21.153Z"
//         },
//         {
//             "_id": "681cf440adb9d7c64aabf786",
//             "salutation": "",
//             "name": "ANURAG VARSHNEY",
//             "phone": "7323288900",
//             "email": "AVARSHNEY@mckinsol.com",
//             "company": "McKinsol Consulting Inc",
//             "website": "",
//             "title": "Managing Partner/Chief Architect",
//             "leadSource": "",
//             "industry": "",
//             "leadStatus": "",
//             "requirement": "",
//             "followUp": "",
//             "type": "",
//             "cem": "Priya",
//             "region": "West Coast",
//             "houseNumber": "",
//             "street": "",
//             "pincodeOrZipcode": "",
//             "city": "",
//             "country": "",
//             "__v": 0,
//             "createdAt": "2025-05-08T18:13:21.153Z",
//             "updatedAt": "2025-05-08T18:13:21.153Z"
//         },
//         {
//             "_id": "681cf440adb9d7c64aabf78a",
//             "salutation": "",
//             "name": "Sneha Nikam",
//             "phone": "9083562483",
//             "email": "sneha.nikam@messer-us.com",
//             "company": "Messer North America, Inc.",
//             "website": "",
//             "title": "Manager - SAP Development and Integration",
//             "leadSource": "",
//             "industry": "",
//             "leadStatus": "",
//             "requirement": "",
//             "followUp": "",
//             "type": "",
//             "cem": "Priya",
//             "region": "West Coast",
//             "houseNumber": "",
//             "street": "",
//             "pincodeOrZipcode": "",
//             "city": "",
//             "country": "",
//             "__v": 0,
//             "createdAt": "2025-05-08T18:13:21.154Z",
//             "updatedAt": "2025-05-08T18:13:21.154Z"
//         },
//         {
//             "_id": "681cf440adb9d7c64aabf78d",
//             "salutation": "",
//             "name": "Craig Doughty",
//             "phone": "5405391604",
//             "email": "craigdoughty@mindsetconsulting.com",
//             "company": "Mindset Consulting, LLC",
//             "website": "",
//             "title": "Account Executive",
//             "leadSource": "",
//             "industry": "",
//             "leadStatus": "",
//             "requirement": "",
//             "followUp": "",
//             "type": "",
//             "cem": "Priya",
//             "region": "West Coast",
//             "houseNumber": "",
//             "street": "",
//             "pincodeOrZipcode": "",
//             "city": "",
//             "country": "",
//             "__v": 0,
//             "createdAt": "2025-05-08T18:13:21.154Z",
//             "updatedAt": "2025-05-08T18:13:21.154Z"
//         },
//         {
//             "_id": "681cf440adb9d7c64aabf7a6",
//             "salutation": "",
//             "name": "Antonio Tombari",
//             "phone": "936-499-7148",
//             "email": "antonio.tombari@pyramidanalytics.com",
//             "company": "Pyramid Analytics",
//             "website": "",
//             "title": "Field Marketing Manager",
//             "leadSource": "",
//             "industry": "",
//             "leadStatus": "",
//             "requirement": "",
//             "followUp": "",
//             "type": "",
//             "cem": "Priya",
//             "region": "West Coast",
//             "houseNumber": "",
//             "street": "",
//             "pincodeOrZipcode": "",
//             "city": "",
//             "country": "",
//             "__v": 0,
//             "createdAt": "2025-05-08T18:13:21.155Z",
//             "updatedAt": "2025-05-08T18:13:21.155Z"
//         },
//         {
//             "_id": "681cf440adb9d7c64aabf7b6",
//             "salutation": "",
//             "name": "Srikanth Kalakonda",
//             "phone": "(480) 917-6000",
//             "email": "srikanth.kalakonda@rogerscorporation.com",
//             "company": "Rogers Corporation",
//             "website": "",
//             "title": "ERP Enterprise Architect 4",
//             "leadSource": "",
//             "industry": "",
//             "leadStatus": "",
//             "requirement": "",
//             "followUp": "",
//             "type": "",
//             "cem": "Priya",
//             "region": "West Coast",
//             "houseNumber": "",
//             "street": "",
//             "pincodeOrZipcode": "",
//             "city": "",
//             "country": "",
//             "__v": 0,
//             "createdAt": "2025-05-08T18:13:21.156Z",
//             "updatedAt": "2025-05-08T18:13:21.156Z"
//         },
//         {
//             "_id": "681cf440adb9d7c64aabf7c3",
//             "salutation": "",
//             "name": "Eric Hagen",
//             "phone": "267-884-3530",
//             "email": "eric.hagen@sap.com",
//             "company": "SAP",
//             "website": "",
//             "title": "Product Manager",
//             "leadSource": "",
//             "industry": "",
//             "leadStatus": "",
//             "requirement": "",
//             "followUp": "",
//             "type": "",
//             "cem": "Priya",
//             "region": "West Coast",
//             "houseNumber": "",
//             "street": "",
//             "pincodeOrZipcode": "",
//             "city": "",
//             "country": "",
//             "__v": 0,
//             "createdAt": "2025-05-08T18:13:21.157Z",
//             "updatedAt": "2025-05-08T18:13:21.157Z"
//         },
//         {
//             "_id": "681cf440adb9d7c64aabf7be",
//             "salutation": "",
//             "name": "Tyler Franks",
//             "phone": "4805457284",
//             "email": "tyler.franks@sap.com",
//             "company": "SAP",
//             "website": "",
//             "title": "S4HANA Center of Excellence",
//             "leadSource": "",
//             "industry": "",
//             "leadStatus": "",
//             "requirement": "",
//             "followUp": "",
//             "type": "",
//             "cem": "Priya",
//             "region": "West Coast",
//             "houseNumber": "",
//             "street": "",
//             "pincodeOrZipcode": "",
//             "city": "",
//             "country": "",
//             "__v": 0,
//             "createdAt": "2025-05-08T18:13:21.156Z",
//             "updatedAt": "2025-05-08T18:13:21.156Z"
//         },
//         {
//             "_id": "681cf440adb9d7c64aabf7d0",
//             "salutation": "",
//             "name": "Prasana Ravichandran",
//             "phone": "9808294285",
//             "email": "prasana.ravichandran@sap.com",
//             "company": "SAP",
//             "website": "",
//             "title": "Sr. CSP",
//             "leadSource": "",
//             "industry": "",
//             "leadStatus": "",
//             "requirement": "",
//             "followUp": "",
//             "type": "",
//             "cem": "Priya",
//             "region": "West Coast",
//             "houseNumber": "",
//             "street": "",
//             "pincodeOrZipcode": "",
//             "city": "",
//             "country": "",
//             "__v": 0,
//             "createdAt": "2025-05-08T18:13:21.157Z",
//             "updatedAt": "2025-05-08T18:13:21.157Z"
//         },
//         {
//             "_id": "681cf440adb9d7c64aabf7d7",
//             "salutation": "",
//             "name": "Kerri Tenbrunsel",
//             "phone": "2246783444",
//             "email": "kerri.tenbrunsel@sap.com",
//             "company": "SAP America",
//             "website": "",
//             "title": "SVP/GM, Head of Business Technology Platform North America",
//             "leadSource": "",
//             "industry": "",
//             "leadStatus": "",
//             "requirement": "",
//             "followUp": "",
//             "type": "",
//             "cem": "Priya",
//             "region": "West Coast",
//             "houseNumber": "",
//             "street": "",
//             "pincodeOrZipcode": "",
//             "city": "",
//             "country": "",
//             "__v": 0,
//             "createdAt": "2025-05-08T18:13:21.158Z",
//             "updatedAt": "2025-05-08T18:13:21.158Z"
//         },
//         {
//             "_id": "681cf440adb9d7c64aabf7f9",
//             "salutation": "",
//             "name": "Senthil Kumar",
//             "phone": "7137852172",
//             "email": "senthil.k@sierradigitalinc.com",
//             "company": "Sierra Digital Inc",
//             "website": "",
//             "title": "",
//             "leadSource": "",
//             "industry": "",
//             "leadStatus": "",
//             "requirement": "",
//             "followUp": "",
//             "type": "",
//             "cem": "Priya",
//             "region": "West Coast",
//             "houseNumber": "",
//             "street": "",
//             "pincodeOrZipcode": "",
//             "city": "",
//             "country": "",
//             "__v": 0,
//             "createdAt": "2025-05-08T18:13:21.160Z",
//             "updatedAt": "2025-05-08T18:13:21.160Z"
//         },
//         {
//             "_id": "681cf440adb9d7c64aabf809",
//             "salutation": "",
//             "name": "HaranVinayagalingam ",
//             "phone": "",
//             "email": "haran.vinayaglanigam@sap.com",
//             "company": "Sr Director, SAP HANA CoE",
//             "website": "",
//             "title": "",
//             "leadSource": "",
//             "industry": "",
//             "leadStatus": "",
//             "requirement": "",
//             "followUp": "",
//             "type": "",
//             "cem": "Priya",
//             "region": "West Coast",
//             "houseNumber": "",
//             "street": "",
//             "pincodeOrZipcode": "",
//             "city": "",
//             "country": "",
//             "__v": 0,
//             "createdAt": "2025-05-08T18:13:21.161Z",
//             "updatedAt": "2025-05-08T18:13:21.161Z"
//         },
//         {
//             "_id": "681cf440adb9d7c64aabf817",
//             "salutation": "",
//             "name": "Joseph Remele",
//             "phone": "6234181778",
//             "email": "jmremele@gmail.com",
//             "company": "SUSE",
//             "website": "",
//             "title": "",
//             "leadSource": "",
//             "industry": "",
//             "leadStatus": "",
//             "requirement": "",
//             "followUp": "",
//             "type": "",
//             "cem": "Priya",
//             "region": "West Coast",
//             "houseNumber": "",
//             "street": "",
//             "pincodeOrZipcode": "",
//             "city": "",
//             "country": "",
//             "__v": 0,
//             "createdAt": "2025-05-08T18:13:21.161Z",
//             "updatedAt": "2025-05-08T18:13:21.161Z"
//         },
//         {
//             "_id": "681cf440adb9d7c64aabf821",
//             "salutation": "",
//             "name": "Eric Seanosky",
//             "phone": "�'+1 (438) 469-0700",
//             "email": "eric.seanosky@consultsda.com",
//             "company": "System Design Analysis (SDA) Inc",
//             "website": "",
//             "title": "",
//             "leadSource": "",
//             "industry": "",
//             "leadStatus": "",
//             "requirement": "",
//             "followUp": "",
//             "type": "",
//             "cem": "Priya",
//             "region": "West Coast",
//             "houseNumber": "",
//             "street": "",
//             "pincodeOrZipcode": "",
//             "city": "",
//             "country": "",
//             "__v": 0,
//             "createdAt": "2025-05-08T18:13:21.161Z",
//             "updatedAt": "2025-05-08T18:13:21.161Z"
//         },
//         {
//             "_id": "681cf440adb9d7c64aabf825",
//             "salutation": "",
//             "name": "Harimander Singh",
//             "phone": "6479803842",
//             "email": "harimanders@illumiti.com",
//             "company": "Technical Consulting Manager",
//             "website": "",
//             "title": "",
//             "leadSource": "",
//             "industry": "",
//             "leadStatus": "",
//             "requirement": "",
//             "followUp": "",
//             "type": "",
//             "cem": "Priya",
//             "region": "West Coast",
//             "houseNumber": "",
//             "street": "",
//             "pincodeOrZipcode": "",
//             "city": "",
//             "country": "",
//             "__v": 0,
//             "createdAt": "2025-05-08T18:13:21.162Z",
//             "updatedAt": "2025-05-08T18:13:21.162Z"
//         },
//         {
//             "_id": "681cf440adb9d7c64aabf82c",
//             "salutation": "",
//             "name": "Lorie Schenck",
//             "phone": "4805047124",
//             "email": "l.schenck@ext.tricentis.com",
//             "company": "Tricentis",
//             "website": "",
//             "title": "",
//             "leadSource": "",
//             "industry": "",
//             "leadStatus": "",
//             "requirement": "",
//             "followUp": "",
//             "type": "",
//             "cem": "Priya",
//             "region": "West Coast",
//             "houseNumber": "",
//             "street": "",
//             "pincodeOrZipcode": "",
//             "city": "",
//             "country": "",
//             "__v": 0,
//             "createdAt": "2025-05-08T18:13:21.163Z",
//             "updatedAt": "2025-05-08T18:13:21.163Z"
//         },
//         {
//             "_id": "681cf440adb9d7c64aabf82d",
//             "salutation": "",
//             "name": "Andrew Prueser",
//             "phone": "2078311050",
//             "email": "a.prueser@tricentis.com",
//             "company": "Tricentis",
//             "website": "",
//             "title": "",
//             "leadSource": "",
//             "industry": "",
//             "leadStatus": "",
//             "requirement": "",
//             "followUp": "",
//             "type": "",
//             "cem": "Priya",
//             "region": "West Coast",
//             "houseNumber": "",
//             "street": "",
//             "pincodeOrZipcode": "",
//             "city": "",
//             "country": "",
//             "__v": 0,
//             "createdAt": "2025-05-08T18:13:21.163Z",
//             "updatedAt": "2025-05-08T18:13:21.163Z"
//         },
//         {
//             "_id": "681cf440adb9d7c64aabf839",
//             "salutation": "",
//             "name": "Abhishek Kaushal",
//             "phone": "908-395-6152",
//             "email": "abkaushal@victoria.com",
//             "company": "VS Service Company, LLC",
//             "website": "",
//             "title": "",
//             "leadSource": "",
//             "industry": "",
//             "leadStatus": "",
//             "requirement": "",
//             "followUp": "",
//             "type": "",
//             "cem": "Priya",
//             "region": "West Coast",
//             "houseNumber": "",
//             "street": "",
//             "pincodeOrZipcode": "",
//             "city": "",
//             "country": "",
//             "__v": 0,
//             "createdAt": "2025-05-08T18:13:21.164Z",
//             "updatedAt": "2025-05-08T18:13:21.164Z"
//         }
//     ]

// const updateCRMUsers = allLeads.map(user => ({
//   ...user, // Convert Mongoose Document to plain object
//   leadId: generateHybridLeadId()
// }));

// console.log("updateCRMUsers", updateCRMUsers);

// for (const user of updateCRMUsers) {
//   const { _id, __v, ...safeUser } = user;  // Remove unwanted fields

//   // await userModel.updateOne(
//   //   { email: safeUser.email, role: { $exists: false } },  // Only if role is not already set
//   //   { $set: { role: "CEM" } }
//   // );
// }

app.listen(port, () => {
    console.log("Server running successfully.")
})

